import { SvgIcons } from '@core/constants/sideIcons';
import { IProject } from '@core/interfaces/projects/projects.interfaces';

export const projects: IProject[] = [
  {
    id: 1,
    icon: SvgIcons.NodeJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Mailer App',
    titleEn: 'Mailer App',
    descriptionEs: 'API backend para envio de emails desde mi portafolio. Envia dos correos: uno para mi y otro para la persona que escribe, confirmando la recepcion.',
    descriptionEn: 'Backend API for sending emails from my portfolio. It sends two emails: one to me and one to the person who writes, confirming receipt.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: Node.js, ExpressJS, JavaScript, Nodemailer, Gmail',
    technologiesEn: 'Technology stack: Node.js, ExpressJS, JavaScript, Nodemailer, Gmail',
    projectLink: 'Link Privado',
    codeLink: 'https://github.com/EleazarGamezD/Mailer-Pf',
  },
  {
    id: 2,
    icon: SvgIcons.NodeJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Notes App',
    titleEn: 'Notes App',
    descriptionEs: 'API backend para manejo de notas tipo post-it con usuarios, CRUD completo de notas y manejo de categorias.',
    descriptionEn: 'Backend API for post-it style notes with users, full notes CRUD, and category management.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: Node.js, ExpressJS, JavaScript, MongoDB, JWT, HTML, CSS',
    technologiesEn: 'Technology stack: Node.js, ExpressJS, JavaScript, MongoDB, JWT, HTML, CSS',
    projectLink: 'https://back-app-notas.vercel.app/',
    codeLink: 'https://github.com/EleazarGamezD/back-app-notas',
  },
  {
    id: 3,
    icon: SvgIcons.NestJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Tu Bodega API',
    titleEn: 'Tu Bodega API',
    descriptionEs: 'API de e-commerce escalable con usuarios, roles, productos, carrito por usuario, control de compras, base de datos Postgres y autenticacion segura.',
    descriptionEn: 'Scalable e-commerce API with users, roles, products, user cart, purchase flow, Postgres database, and secure authentication.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: Node.js, NestJS, TypeScript, PostgreSQL, TypeORM, JWT, Swagger',
    technologiesEn: 'Technology stack: Node.js, NestJS, TypeScript, PostgreSQL, TypeORM, JWT, Swagger',
    projectLink: 'https://tu-bodega.vercel.app/',
    codeLink: 'https://github.com/EleazarGamezD/Tu-Bodega',
  },
  {
    id: 4,
    icon: SvgIcons.NestJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Pokedex',
    titleEn: 'Pokedex',
    descriptionEs: 'Backend conectado a pokeapi.co para carga inicial de datos (seed), con MongoDB Atlas usando NestJS.',
    descriptionEn: 'Backend connected to pokeapi.co for data seeding, with MongoDB Atlas using NestJS.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: NestJS, Node.js, MongoDB Atlas, JavaScript, TypeScript, Docker',
    technologiesEn: 'Technology stack: NestJS, Node.js, MongoDB Atlas, JavaScript, TypeScript, Docker',
    projectLink: '',
    codeLink: 'https://github.com/EleazarGamezD/pokedex',
  },
  {
    id: 5,
    icon: SvgIcons.NestJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'GG-Shop',
    titleEn: 'GG-Shop',
    descriptionEs: 'Backend de app web e-commerce con productos, autenticacion de usuarios, Postgres con TypeORM y chat en tiempo real por WebSockets.',
    descriptionEn: 'Backend for an e-commerce web app with products, user authentication, Postgres with TypeORM, and real-time chat with WebSockets.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: NestJS, Node.js, PostgreSQL, TypeORM, JavaScript, TypeScript, WebSockets, Swagger, Docker',
    technologiesEn: 'Technology stack: NestJS, Node.js, PostgreSQL, TypeORM, JavaScript, TypeScript, WebSockets, Swagger, Docker',
    projectLink: '',
    codeLink: 'https://github.com/EleazarGamezD/gg-shop',
  },
  {
    id: 6,
    icon: SvgIcons.NestJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Proyecto WS-Client',
    titleEn: 'WS-Client Project',
    descriptionEs: 'Proyecto frontend pequeno conectado a la API GG-shop para servicio de WebSocket.',
    descriptionEn: 'Small frontend project connected to the GG-shop API for WebSocket service.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: Node.js, TypeScript, CSS, HTML',
    technologiesEn: 'Technology stack: Node.js, TypeScript, CSS, HTML',
    projectLink: '',
    codeLink: 'https://github.com/EleazarGamezD/ws-client',
  },
  {
    id: 7,
    icon: SvgIcons.AngularIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Rick and Morty Angular Test',
    titleEn: 'Rick and Morty Angular Test',
    descriptionEs: 'Proyecto tipo ensayo conectado a rickandmortyapi.com para practicar tecnicas frontend a nivel junior.',
    descriptionEn: 'Practice project connected to rickandmortyapi.com to learn junior-level frontend techniques.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: Node.js, TypeScript, JavaScript, CSS, HTML, Angular, Angular Material',
    technologiesEn: 'Technology stack: Node.js, TypeScript, JavaScript, CSS, HTML, Angular, Angular Material',
    projectLink: 'https://rickandmory-angulartest.netlify.app/',
    codeLink: 'https://github.com/EleazarGamezD/Rick-And-Morty-Angular-Test-',
  },
  {
    id: 8,
    icon: SvgIcons.NodeJsIcon,
    images: ['assets/images/click.gif'],
    titleEs: 'Cursos',
    titleEn: 'Courses',
    descriptionEs: 'Coleccion de proyectos de estudio backend, organizados por ejercicios: auth, compras, mailer, y otros modulos practicos.',
    descriptionEn: 'Collection of backend learning projects, organized by exercises: auth, shopping, mailer, and other practical modules.',
    resume: '',
    technologiesEs: 'Stack de tecnologias: Node.js, TypeScript, JavaScript, MongoDB, CSS, HTML, React, Postman',
    technologiesEn: 'Technology stack: Node.js, TypeScript, JavaScript, MongoDB, CSS, HTML, React, Postman',
    projectLink: '',
    codeLink: 'https://github.com/EleazarGamezD/CURSO',
  },
];
