# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Angular Project
        run: ng build --prod
      - name: Run Tests
        run: npm test
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        run: |
          npm install -g angular-cli-ghpages
          ngh --dir=dist/my-portfolio
